### ISSUE TITLE
Conflicting peer dependency: knex@0.14.2

### ISSUE THREAD

**Issue by avshukan** [hexlet-boilerplates/fastify-nodejs-application#33]
Добрый день!
Какие-то конфликты при установке пакетов
`

> $ npm i
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> 
> added 1616 packages, and audited 1617 packages in 34s
> 
> 101 packages are looking for funding
>   run `npm fund` for details
> 
> 36 vulnerabilities (1 low, 9 moderate, 25 high, 1 critical)
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> 
> Run `npm audit` for details.
> sa@miac-3420200006:~/Documents/Hexlet/js-web-development-project-lvl4
> $ npm audit fix
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: objection@2.2.17
> npm ERR! Found: knex@0.21.21
> npm ERR! node_modules/knex
> npm ERR!   knex@"^0.21.19" from the root project
> npm ERR!   peer knex@"<0.95.0" from objection@2.2.17
> npm ERR!   node_modules/objection
> npm ERR!     objection@"^2.2.15" from the root project
> npm ERR!     objection@"^2.2.15" from fastify-objectionjs@0.4.0
> npm ERR!     node_modules/fastify-objectionjs
> npm ERR!       fastify-objectionjs@"^0.4.0" from the root project
> npm ERR!     1 more (objection-unique)
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer knex@"<0.95.0" from objection@2.2.17
> npm ERR! node_modules/objection
> npm ERR!   objection@"^2.2.15" from the root project
> npm ERR!   objection@"^2.2.15" from fastify-objectionjs@0.4.0
> npm ERR!   node_modules/fastify-objectionjs
> npm ERR!     fastify-objectionjs@"^0.4.0" from the root project
> npm ERR!   1 more (objection-unique)
> npm ERR! 
> npm ERR! Conflicting peer dependency: knex@0.14.2
> npm ERR! node_modules/knex
> npm ERR!   peer knex@"<0.95.0" from objection@2.2.17
> npm ERR!   node_modules/objection
> npm ERR!     objection@"^2.2.15" from the root project
> npm ERR!     objection@"^2.2.15" from fastify-objectionjs@0.4.0
> npm ERR!     node_modules/fastify-objectionjs
> npm ERR!       fastify-objectionjs@"^0.4.0" from the root project
> npm ERR!     1 more (objection-unique)
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /home/sa/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/sa/.npm/_logs/2021-10-19T02_59_54_646Z-debug.log
> sa@miac-3420200006:~/Documents/Hexlet/js-web-development-project-lvl4
> $

 
`

**Comment by corsicanec82** [comment]
Все зависимости в репозитории обновлены и на данный момент конфликтов нет.
Этот ишью я закрываю, при необходимости вы сможете его открыть заново.
